services:
  postgres-filmes:
    image: postgres:16
    container_name: cinet-postgres-filmes
    environment:
      POSTGRES_DB: cinet_filmes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_filmes_data:/var/lib/postgresql/data
    networks:
      - cinet-network

  postgres-sessoes:
    image: postgres:16
    container_name: cinet-postgres-sessoes
    environment:
      POSTGRES_DB: cinet_sessoes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_sessoes_data:/var/lib/postgresql/data
    networks:
      - cinet-network

  cinet-filme-service:
    image: cinet-filme-service
    container_name: cinet-filme-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres-filmes
    networks:
      - cinet-network

  cinet-sessao-service:
    image: cinet-sessao-service
    container_name: cinet-sessao-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres-sessoes
      - cinet-filme-service
    networks:
      - cinet-network

volumes:
  postgres_filmes_data:
  postgres_sessoes_data:

networks:
  cinet-network:
    driver: bridge