apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-sessoes-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinet-postgres-sessoes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinet-postgres-sessoes
  template:
    metadata:
      labels:
        app: cinet-postgres-sessoes
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: cinet_sessoes
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-sessoes-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: cinet-postgres-sessoes
spec:
  selector:
    app: cinet-postgres-sessoes
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP